/**:
  robot_state_publisher:
    ros__parameters:
      ignore_timestamp: False
      publish_frequency: 20.0
  hardware:
    ros__parameters:
      joint_update_freq: 500.0
      actuator_update_freq: 10.0