/**:
  robot_state_publisher:
    ros__parameters:
      ignore_timestamp: False
      publish_frequency: 20.0
  hardware:
    ros__parameters:
      joint_update_freq: 0.0
      actuator_update_freq: 1.0
      initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5, -0.5, -0.5, -0.5, 0.0, 0.35]
  controller:
    ros__parameters:
      joint_effort_filter_window: 3
      mass_threshold: 0.5
      verbose: False
      debug: False
      stiffness: 1000.0
      microspine_max_force: 15.0
      friction_coefficient: 0.5
      clearance: 0.05
      effort_limit: 1.4
      normalization: 0.01
      tracking: 2000.0
      joint_step: 0.01
      default_configuration: "climb"
      sim_wrench: [13.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  step_planner:
    ros__parameters:
      step_height: 0.1
      step_length: 0.15
      swing_velocity: 0.005
      engage_force: [3.0, 0.0, -5.0, 0.0, 0.0, 0.0]
      engage_tolerance: 1.0
      disengage_force: [-5.0, 5.0, 5.0, 0.0, 0.0, 0.0]
      disengage_frequency: 0.5
      disengage_tolerance: 3.0
      contact_threshold: 5.0
      snag_threshold: 5.0
      foothold_tolerance: 0.01
      retry_distance: 0.1
      angular_scaling: 0.1