/**:
  ros__parameters:
    joint_names: [
      shoulder_joint_1, shoulder_joint_2, shoulder_joint_3, shoulder_joint_4,
      wing_joint_1, wing_joint_2, wing_joint_3, wing_joint_4,
      knee_joint_1, knee_joint_2, knee_joint_3, knee_joint_4,
      spine_joint, tail_joint]
    actuator_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
    actuator_models: [XM430-W350-T]
    body_frame: root
    end_effector_frames: [wrist_1, wrist_2, wrist_3, wrist_4, tail_tip]
    contact_frames: [gripper_1, gripper_2, gripper_3, gripper_4, tail_contact]
    wrist_types: [gravity, gravity, gravity, gravity, fixed]
    contact_types: [microspine, microspine, microspine, microspine, tail]